server:
  port: 8085

spring:
  application:
    name: edusphere-api-gateway

gateway:
  routes:
    auth-service: http://localhost:8081
    course-service: http://localhost:8082
    payment-service: http://localhost:8083
    chat-service: http://localhost:8084
    notification-service: http://localhost:8086
