apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: edusphere-lms
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: dnyaneshvarchavan/edusphere-backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: DB_URL
              value: jdbc:mysql://mysql-service:3306/edusphere_lms?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
            - name: DB_USERNAME
              value: root
            - name: DB_PASSWORD
              value: root
            - name: DB_DRIVER
              value: com.mysql.cj.jdbc.Driver
            - name: JWT_SECRET
              value: ffb6ea25bcbdc649276380abd550fc6d60f6b39c01aba42f64fe117cc7f7118e
            - name: FRONTEND_URL
              value: http://localhost:3000
            - name: STORAGE_PROVIDER
              value: local
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 45
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: edusphere-lms
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  selector:
    app: backend
  type: ClusterIP
